### ISSUE TITLE
[typescript]: key that contain white-space or quote was not quoted

### ISSUE THREAD

**Issue by DrSensor** [evestera/json_typegen#10]
Awesome works! Thank you for creating this crates.

I notice this false behavior which only happen in typescript:
```json
{
  "states": {
    "alphaGo": {
      "on": {
        "": "betaRust"
      }
    },
    "nightl'y update": {
      "on": {
        "every 4 weeks": "channel:beta"
      }
    },
    "b": {
      "on": {
        "ON": "initial D",
        "FALSE_ALARM": "c"
      }
    }
  }
}
```
```ts
interface Root {
    states: States;
}
interface States {
    alphaGo: AlphaGo;
    nightl'y update: NightlYUpdate;
    b: B;
}
interface AlphaGo {
    on: On;
}
interface On {
    "": string;
}
interface NightlYUpdate {
    on: On2;
}
interface On2 {
    every 4 weeks: string;
}
interface B {
    on: On3;
}
interface On3 {
    ON: string;
    FALSE_ALARM: string;
}
```
The empty string key parsed correctly but some keys that have white-space or quote were not surrounded with double-quote. At least the interface name is correct 🤔

**Comment by evestera** [comment]
Ah, seems to be a simple oversight on my part when adding a regex, checking if a string *contains* a valid identifier rather than if it *is* a valid identifier. Thanks for the bug report. I should get a fixed version released pretty soon.

**Comment by evestera** [comment]
Made [a release](https://github.com/evestera/json_typegen/releases/tag/v0.3.3) with the fix included now.
