### ISSUE TITLE
Current web version broken: Missing Generics

### ISSUE THREAD

**Issue by theduke** [evestera/json_typegen#9]
Hey, very useful crate!

The CLI works fine, but the current web version produces invalid code with missing generic params.

Eg:
```
struct Root {
  a: Vec,
  b: Option,
}
```

**Comment by evestera** [comment]
Thanks, and thank you for the bug report.

Turns out I had forgotten to escape brackets in the output code, so stuff like `<i64>` was interpreted as a tag. Should be fixed now.
